version: '3.7'

services:
  keeper-db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: keeper
      POSTGRES_DB: keeper_events
      POSTGRES_PASSWORD: events123
