"""tables

Revision ID: 034529bc5e0b
Revises: 
Create Date: 2023-03-29 13:22:16.175008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034529bc5e0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_user_telegram_id'))
    )
    op.create_table('config',
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('can_see_friends', sa.Integer(), nullable=True),
    sa.Column('can_see_wish', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_config_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config'))
    )
    op.create_index(op.f('ix_config_user_id'), 'config', ['user_id'], unique=False)
    op.create_table('event',
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('celebrating_person_id', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('start_event_time', sa.DateTime(), nullable=False),
    sa.Column('notification_time', sa.Time(), nullable=True),
    sa.Column('postponement_time', sa.DateTime(), nullable=True),
    sa.Column('crontab', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['celebrating_person_id'], ['user.id'], name=op.f('fk_event_celebrating_person_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_event_created_by_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    op.create_index(op.f('ix_event_celebrating_person_id'), 'event', ['celebrating_person_id'], unique=False)
    op.create_index(op.f('ix_event_created_by'), 'event', ['created_by'], unique=False)
    op.create_table('invite',
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('sender_is_accepted', sa.Boolean(), nullable=True),
    sa.Column('receiver_is_accepted', sa.Boolean(), nullable=True),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('receiver_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], name=op.f('fk_invite_receiver_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('fk_invite_sender_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invite'))
    )
    op.create_index(op.f('ix_invite_receiver_id'), 'invite', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_invite_sender_id'), 'invite', ['sender_id'], unique=False)
    op.create_table('wish_list',
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_wish_list_owner_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wish_list'))
    )
    op.create_index(op.f('ix_wish_list_owner_id'), 'wish_list', ['owner_id'], unique=False)
    op.create_table('wish_item',
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.Column('wish_list_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['wish_list_id'], ['wish_list.id'], name=op.f('fk_wish_item_wish_list_id_wish_list'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wish_item'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wish_item')
    op.drop_index(op.f('ix_wish_list_owner_id'), table_name='wish_list')
    op.drop_table('wish_list')
    op.drop_index(op.f('ix_invite_sender_id'), table_name='invite')
    op.drop_index(op.f('ix_invite_receiver_id'), table_name='invite')
    op.drop_table('invite')
    op.drop_index(op.f('ix_event_created_by'), table_name='event')
    op.drop_index(op.f('ix_event_celebrating_person_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_config_user_id'), table_name='config')
    op.drop_table('config')
    op.drop_table('user')
    # ### end Alembic commands ###
