"""add new table3

Revision ID: 1c19a9b4283b
Revises: e355d73346fd
Create Date: 2023-04-03 14:29:29.637721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c19a9b4283b'
down_revision = 'e355d73346fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
