"""add table can see wish

Revision ID: dccd283c2a24
Revises: 034529bc5e0b
Create Date: 2023-03-30 12:52:13.500076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccd283c2a24'
down_revision = '034529bc5e0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
